# Generated by Django 5.0.7 on 2024-08-21 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Auction id')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('desc', models.TextField(verbose_name='Description')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('entry_fee', models.IntegerField(verbose_name='Entry Fee')),
                ('open_bid', models.IntegerField(verbose_name='Openning Bid')),
                ('auct_start', models.DateTimeField(verbose_name='Auction Start Date & Time')),
                ('auct_end', models.DateTimeField(verbose_name='Auction End Date & Time')),
                ('image', models.ImageField(upload_to='Images/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'db_table': 'auctions',
                'ordering': ['-auct_start'],
            },
        ),
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_name', models.CharField(max_length=50, verbose_name='Bidder Name')),
                ('bid_amt', models.IntegerField(verbose_name='Bid Amount')),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Auction.auction', verbose_name='Auction id')),
            ],
            options={
                'verbose_name': 'Bidder',
                'verbose_name_plural': 'Bidders',
                'db_table': 'bidders',
                'ordering': ['-bid_amt'],
            },
        ),
    ]
