# Generated by Django 5.0.7 on 2024-09-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Auction', '0002_bid_participant_delete_bidder'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participant',
            table='participants',
        ),
    ]
