# Generated by Django 5.0.7 on 2024-09-24 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Auction', '0006_alter_bid_options_rename_user_name_bid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auct_end',
        ),
        migrations.AddField(
            model_name='auction',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), verbose_name='Auction Duration'),
        ),
    ]
